# Generated by Django 5.2.17 on 2026-09-20 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='purpose',
            field=models.CharField(choices=[('email_verification', 'Email verification'), ('login', 'Login')], default='email_verification', max_length=32),
        ),
        migrations.CreateModel(
            name='SocialIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google')], max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('email_at_link', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='unique_social_provider_subject'), models.UniqueConstraint(fields=('provider', 'user'), name='unique_social_provider_user')],
            },
        ),
    ]
