# Generated by Django 5.2.17 on 2026-09-20 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_onetimepassword_purpose_socialidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('login_otp', 'Login OTP')], max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purpose', 'created_at'], name='auth_app_ca_purpose_659c6c_idx')],
            },
        ),
    ]
